import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "./components/header/Header";
import Sidbar from "./components/aside/Sidbar";
import "./styles/darkmode.scss";
import Theprovider from "./Theprovider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theprovider>
          <Header />
          <div className="flex">
            <Sidbar />
            {children}
          </div>
        </Theprovider>
      </body>
    </html>
  );
}
